/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d8dadc',
        'on-secondary-container': '#785a1a',
        'surface-container-low': '#f2f4f6',
        'surface-tint': '#565e74',
        'tertiary-container': '#0b1c30',
        'on-secondary-fixed-variant': '#5d4201',
        'on-tertiary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'primary-fixed': '#dae2fd',
        'on-error-container': '#93000a',
        'on-primary-container': '#7c839b',
        'surface-container-high': '#e6e8ea',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3133',
        'on-surface-variant': '#45464d',
        'on-primary': '#ffffff',
        surface: '#f7f9fb',
        'on-tertiary-fixed': '#0b1c30',
        'surface-container-highest': '#e0e3e5',
        'secondary-fixed-dim': '#e9c176',
        secondary: '#775a19',
        tertiary: '#000000',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed488',
        error: '#ba1a1a',
        'inverse-primary': '#bec6e0',
        'tertiary-fixed-dim': '#b7c8e1',
        'on-surface': '#191c1e',
        'on-primary-fixed-variant': '#3f465c',
        'primary-fixed-dim': '#bec6e0',
        'surface-bright': '#f7f9fb',
        'tertiary-fixed': '#d3e4fe',
        'primary-container': '#131b2e',
        'on-background': '#191c1e',
        'outline-variant': '#c6c6cd',
        'on-tertiary-fixed-variant': '#38485d',
        background: '#f7f9fb',
        primary: '#000000',
        'on-secondary-fixed': '#261900',
        'on-primary-fixed': '#131b2e',
        'surface-container': '#eceef0',
        'secondary-fixed': '#ffdea5',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary-container': '#75859d',
        outline: '#76777d',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-xs': '4px',
        'stack-xl': '64px',
        'stack-lg': '32px',
        'container-max': '1280px',
        'stack-md': '16px',
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'label-sm': ['Inter'],
        'body-lg': ['Inter'],
        'label-md': ['Inter'],
        'headline-sm': ['Libre Caslon Text'],
        'display-lg-mobile': ['Libre Caslon Text'],
        'title-lg': ['Inter'],
        'display-lg': ['Libre Caslon Text'],
        'headline-md': ['Libre Caslon Text'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};